
# spring.kafka.properties:
#   sasl.mechanism: PLAIN
#   bootstrap.servers: localhost:9092

# spring.kafka.producer:
#   bootstrap-servers: localhost:9092
#   key-serializer: org.apache.kafka.common.serialization.StringSerializer
#   value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#   buffer-memory: 33554432
#   retries: 0


spring.application.name: quiz-manager

server.port: 7000
server.error.include-message: always


springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: dev.agasen.microsrv
  pathsToMatch: /**
  cache.disabled: true

  swagger-ui:
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
    oauth:
      clientId: writer
      clientSecret: secret-writer
      useBasicAuthenticationWithAccessCodeGrant: true
  oAuthFlow:
    authorizationUrl: https://localhost:8443/oauth2/authorize
    tokenUrl: https://localhost:8443/oauth2/token

app:
  kafka:
    question-topic: question
  scheduler:
    threadPoolSize: 10
    taskQueueSize: 100

  eureka-username: u
  eureka-password: p
  eureka-server: localhost
  auth-server: localhost


# value of issuer-uri should match the AuthenticationServerSettings::issuer, see Bean Config in the Auth Server
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999


eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

# see https://springdoc.org/index.html#how-can-i-deployspringdoc-openapi-ui-behind-a-reverse-proxy.
# this is added since a reverse proxy / edge server is used
server.forward-headers-strategy: framework

logging:
  level:
    root: INFO
    dev.agasen: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE