spring.application.name: question

server.port: 7001
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
# this is to satisfy Docker testing
# TODO: Create a volume for Table DDL
# spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.ddl-auto: none


spring.datasource:
  url: jdbc:mysql://localhost:3307/question-db
  # url: jdbc:mysql://localhost/question-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging.level: 
  root: INFO
  dev.agasen: DEBUG
  org.hibernate.SQL: DEBUG 


---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource.url: jdbc:mysql://mysql/question-db

spring.jpa.hibernate.ddl-auto: none