
server.port: 8888

# this is using local repository
# repo is in root package
spring.cloud.config.server.native.searchLocations: file:${PWD}/config-repo

management.endpoint.health.show-details: "ALWAYS" 
management.endpoints.web.exposure.include: "*"


logging.level: 
  root: info

---
spring.config.activate.on-profile: docker 
spring.cloud.config.server.native.searchLocations: file:/config-repo