
server.port: 8443

spring.application.name: gateway

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost
  auth-server: localhost

server.ssl:
  key-store-type: PKCS12 
  key-store: classpath:keystore/edge.p12 
  key-store-password: password 
  key-alias: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999

spring.cloud.gateway.routes:
  - id: quiz-manager
    uri: lb://quiz-manager
    predicates:
    - Path=/manager/quiz/**

  - id: oauth2-server
    uri: lb://auth-server
    predicates:
    - Path=/oauth2/**

  - id: oauth2-login
    uri: lb://auth-server
    predicates:
    - Path=/login/**

  - id: oauth2-error
    uri: lb://auth-server
    predicates:
    - Path=/error/**

  - id: config-server
    uri: http://${app.config-server}:8888
    predicates:
    - Path=/config/*
    filters:
    - RewritePath=/config/(?<segment>.*), /$\{segment}

  - id: quiz-manager-swagger-ui
    uri: lb://quiz-manager
    predicates:
    - Path=/openapi/** 

  - id: question-get
    uri: lb://quiz-manager
    predicates:
    - Path=/question/**
    - Method=GET

  - id: eureka-api
    uri: http://${app.eureka-server}:8761
    predicates:
    - Path=/eureka/api/{segment}
    filters:
    - SetPath=/eureka/{segment}

  - id: eureka-web-start
    uri: http://${app.eureka-server}:8761
    predicates:
    - Path=/eureka/web
    filters:
    - SetPath=/

  - id: eureka-web-other
    uri: http://${app.eureka-server}:8761
    predicates:
    - Path=/eureka/**


# Configure spring boot actuator
management:
  # this is to enable 
  endpoint.gateway.enabled: true
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"

# Logging
logging.level: 
  root: INFO
  org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO 
  org.springframework.cloud.gateway: TRACE
  org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE